loja/loja/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

loja/main/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home,name='home'),
    path('category-list',views.category_list,name='category-list'),
    path('marca-list',views.marca_list,name='marca-list'),
    path('product-list',views.product_list,name='product-list'),
    path('category-product-list/<int:cat_id>',views.category_product_list,name='category-product-list'),
    path('marca-product-list/<int:marca_id>',views.marca_product_list,name='marca-product-list'),
    path('product/<str:slug>/<int:id>',views.product_detail,name='product-detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loja/main/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.utils.html import mark_safe

class Banner(models.Model):
    img = models.ImageField(upload_to="banner_imgs/")
    alt_text = models.CharField(max_length = 300)

    class Meta:
        verbose_name_plural = '1. Banners'

    def image_tag_path(self):
        return mark_safe('<img src="%s" width="100"/>' %(self.img.url))

    def __str__(self):
        return self.alt_text


class Category(models.Model):
    title=models.CharField(max_length=180)
    image=models.ImageField(upload_to="cat_imgs/", null=True)

    class Meta:
        verbose_name_plural = '2. Categories'

    def image_tag_path(self):
        return mark_safe('<img src="%s" width="50" height="30" />' %(self.image.url))

    def __str__(self):
        return self.title


class Marca(models.Model):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to="marca_imgs/", null=True)

    class Meta:
        verbose_name_plural = '3. Marcas'

    def __str__(self):
        return self.title


class Color(models.Model):
    title=models.CharField(max_length=100)
    color_codigo=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '4. Colors'

    def color_tag_path(self):
        return mark_safe('<div style="width:50px; height:30px; background:%s"></div>' % (self.color_codigo))

    def __str__(self):
        return self.title
    

class Size(models.Model):
    title=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '5. Sizes'

    def __str__(self):
        return self.title
    

class Product(models.Model):
    title=models.CharField(max_length=200)
    slug=models.CharField(max_length=400)
    detail=models.TextField()
    specs=models.TextField()
    marca=models.ForeignKey(Marca, on_delete=models.CASCADE)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    color=models.ForeignKey(Color, on_delete=models.CASCADE)
    size=models.ForeignKey(Size, on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    produto_em_destaque=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = '6. Products'

    def __str__(self):
        return self.title
    

class ProductAttribute(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    size = models.ForeignKey(Size,on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    image=models.ImageField(upload_to="product_imgs/", null=True)

    class Meta:
        verbose_name_plural = '7. ProductAttributes'

    def __str__(self):
        return self.product.title
    
    def image_tag_path(self):
        return mark_safe('<img src="%s" width="50" height="30" />' %(self.image.url))

loja/main/views.py
from django.shortcuts import render
from .models import Category, Marca, Product, ProductAttribute, Banner

def home(request):
    banners = Banner.objects.all().order_by('-id')
    data = Product.objects.filter(produto_em_destaque=True).order_by('-id')
    return render(request, 'index.html', {'data':data, 'banners':banners})


def category_list(request):
    data=Category.objects.all().order_by('-id')
    return render(request, 'category_list.html',{'data':data})

def marca_list(request):
    data=Marca.objects.all().order_by('-id')
    return render(request, 'marca_list.html',{'data':data})

def product_list(request):
    data=Product.objects.all().order_by('-id')
    cats=Product.objects.distinct().values('category__title','category__id')
    marcas=Product.objects.distinct().values('marca__title','marca__id')
    colors=ProductAttribute.objects.distinct().values('color__title','color__id','color__color_codigo')
    sizes=ProductAttribute.objects.distinct().values('size__title','size__id')

    return render(request, 'product_list.html',
    {
        'data':data,
        'cats':cats,
        'marcas':marcas,
        'colors':colors,
        'sizes':sizes,
    }
    )

def category_product_list(request, cat_id):
    category=Category.objects.get(id=cat_id)
    data=Product.objects.filter(category=category).order_by('-id')
    cats=Product.objects.distinct().values('category__title','category__id')
    marcas=Product.objects.distinct().values('marca__title','marca__id')
    colors=ProductAttribute.objects.distinct().values('color__title','color__id','color__color_codigo')
    sizes=ProductAttribute.objects.distinct().values('size__title','size__id')
    
    return render(request, 'category_product_list.html',
    {
        'data':data,
        'cats':cats,
        'marcas':marcas,
        'colors':colors,
        'sizes':sizes,
    }
    )

def marca_product_list(request, marca_id):
    marca=Marca.objects.get(id=marca_id)
    data=Product.objects.filter(marca=marca).order_by('-id')
    cats=Product.objects.distinct().values('category__title','category__id')
    marcas=Product.objects.distinct().values('marca__title','marca__id')
    colors=ProductAttribute.objects.distinct().values('color__title','color__id','color__color_codigo')
    sizes=ProductAttribute.objects.distinct().values('size__title','size__id')
    
    return render(request, 'marca_product_list.html',
    {
        'data':data,
        'cats':cats,
        'marcas':marcas,
        'colors':colors,
        'sizes':sizes,
    }
    )

def product_detail(request, slug, id):
    product=Product.objects.get(id=id)
    
    return render(request, 'product_detail.html',
    {
        'data':product,
    }
    )

loja/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Loja Django 2022</title>
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<!-- Bootstrap 4 JS -->
	<script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
	<!-- CustomJs -->
	<link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
	<script type="text/javascript" src="{% static 'custom.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-success">
		<div class="container">
		  <a class="navbar-brand" href="/">Loja Django</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		  	<form class="form-inline my-2 my-lg-0" action="/search">
		      <div class="input-group">
				  <input name="q" type="text" class="form-control" placeholder="Pesquisar" />
				  <div class="input-group-append">
				    <button class="btn btn-dark" type="submit" id="button-addon2">Pesquisar</button>
				  </div>
				</div>
		    </form>
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'category-list'%}">Categorias</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'marca-list'%}">Marcas</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href=""><i class="fa fa-shopping-cart"></i> Carrinho (<span class="cart-list"></span>)</a>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fa fa-user"></i> Minha Conta
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		      
		        	<a class="dropdown-item" href="">Painel</a>
		        	<a class="dropdown-item" href="">Sair</a>
	        	
	        		<a class="dropdown-item" href="">Login</a>
		          <a class="dropdown-item" href="">Cadastrar</a>
		    
		        </div>
		      </li>
		    </ul>
		  </div>
		</div>
    </nav>
    
    {% block content %}
    {% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top container">
    <div class="row">
        <div class="col-12 col-md">
        <a href="#">Loja Django 2022</a>
        <small class="d-block mb-3 text-muted">&copy; 2022</small>
        </div>
        <div class="col-6 col-md">
        <h5>Recursos</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Produtos Legais</a></li>
            <li><a class="text-muted" href="#">Recurso Aleatórios</a></li>
            <li><a class="text-muted" href="#">Recursos em Equipe</a></li>
            <li><a class="text-muted" href="#">Produtos Para Desenvolvedores</a></li>
            <li><a class="text-muted" href="#">Outros</a></li>
            <li><a class="text-muted" href="#">Última Oportunidade</a></li>
        </ul>
        </div>
        <div class="col-6 col-md">
        <h5>Recursos</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Recursos</a></li>
            <li><a class="text-muted" href="#">Nome Do Recurso</a></li>
            <li><a class="text-muted" href="#">Outro Recurso</a></li>
            <li><a class="text-muted" href="#">Recurso Final</a></li>
        </ul>
        </div>
        <div class="col-6 col-md">
        <h5>Sobre</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Equipe</a></li>
            <li><a class="text-muted" href="#">Localizações</a></li>
            <li><a class="text-muted" href="#">Privacidade</a></li>
            <li><a class="text-muted" href="#">Termos</a></li>
        </ul>
        </div>
    </div>
    </footer>
</body>
</html>

loja/main/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">

	<h3 class="my-4 border-bottom pb-1">Categorias</h3>
	<div class="row">
		{% if data %}
			{% for cat in data %}
				<div class="col-md-3 mb-4">
					<div class="card shadow">
					<a href="/category-product-list/{{cat.id}}"><img src="/media/{{cat.image}}" class="card-img-top" alt="{{cat.title}}" /></a>
					<div class="card-body">
						<h6 class="card-text"><a href="/category-product-list/{{cat.id}}">{{cat.title}}</a></h6>
					</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

loja/main/templates/category_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			
			<h3 class="mb-4 border-bottom pb-1">
				Produtos
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader"></p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
                            <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
                            <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.price}}" />
                            <input type="hidden" class="form-control product-qty-{{product.id}}" value="{{product.id}}" />
                            <input type="hidden" class="form-control product-qty-{{product.id}}" value="{{product.title}}" />
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index=""><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="" data-limit="3" class="btn btn-dark btn-sm">Carregar mais  <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}

loja/main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
    {% else %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
    {% endif %}
    {% endfor %}
  </ol>
  
  <div class="carousel-inner">
    {% for banner in banners %}
    {% if forloop.counter == 1 %}
    <div class="carousel-item active">
      {% else %}
      <div class="carousel-item">
        {% endif %}
      <img src="/media/{{banner.img}}" class="d-block w-100" alt="...">
    </div>
    {% endfor %}
   
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Proximo</span>
  </a>
</div>
</div>
<main class="container my-4">
	
	<h3 class="my-4 border-bottom pb-1">Produtos Em Destaques</h3>
	<div class="row">
   {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
			    <h5 class="card-text"><a href=""></a>{{product.title}}</h5>
          <h6>R${{product.productattribute_set.first.price}}<span class=""></span></h6>
			  </div>
			  <div class="card-footer">
         
          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
			  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
         
			  	<button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
         
          <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
       
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
    {% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">Todos Produtos <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

loja/main/templates/marca_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">

	<h3 class="my-4 border-bottom pb-1">Marcas</h3>
	<div class="row">
		{% if data %}
			{% for marca in data %}
				<div class="col-md-3 mb-4">
					<div class="card shadow">
					<a href="/marca-product-list/{{marca.id}}"><img src="/media/{{marca.image}}" class="card-img-top" alt="{{marca.title}}" /></a>
					<div class="card-body">
						<h6 class="card-text"><a href="/marca-product-list/{{marca.id}}">{{marca.title}}</a></h6>
					</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

loja/main/templates/marca_product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			
			<h3 class="mb-4 border-bottom pb-1">
				Produtos
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader"></p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
                            <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
                            <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.price}}" />
                            <input type="hidden" class="form-control product-qty-{{product.id}}" value="{{product.id}}" />
                            <input type="hidden" class="form-control product-qty-{{product.id}}" value="{{product.title}}" />
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index=""><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="" data-limit="3" class="btn btn-dark btn-sm">Carregar mais  <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}

loja/main/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">

    <h3 class="my-4 border-bottom pb1">{{data.title}}</h3>
	<div class="row">

        <div class="col-md-4">
            <img id="zoom_01" data-zoom-image="/media/{{data.productattribute_set.first.image}}" src="/media/{{data.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}">
        </div>
        <div class="col-md-8">
            <p>{{data.detail}}</p>
            <hr/>
            <table class="table table-bordered">
                <tr>
                    <th>Preço</th>
                    <th>R${{data.productattribute_set.first.price}}</th>
                </tr>
                <tr>
                    <th>Cores</th>
                        <td>
                            {% for p_attr in data.productattribute_set.all %}
                            <button class="btn btn-lg choose-color" style="background-color:{{p_attr.color__color_codigo}}"></button>
                            {% endfor %}
                        </td>
                </tr>
                <tr>
                    <th>Tamanhos</th>
                    <td>
                        {% for p_attr in data.productattribute_set.all %}
                        <button class="btn btn-lg choose-color">{{p_attr.size.title}}</button>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>Price</th>
                    <th>$ <span class="product-price-{{data.id}}">{{data.productattribute_set.first.price}}</span></th>
                </tr>
            </table>
            <hr/>
            <div class="input-group my-3" style="width:30%;">
                <input type="number" value="1" class="form-control product-qty-{{data.id}}" id="productQty" />
                <div class="input-group-append">
                    <input type="hidden" class="product-image-{{data.id}}" value="{{data.productattribute_set.first.image}}" />
                        <input type="hidden" class="product-id-{{data.id}}" value="{{data.id}}" />
                        <input type="hidden" class="product-title-{{data.id}}" value="{{data.title}}" />
                    <button class="btn btn-success btn-sm add-to-cart" data-index="{{data.id}}" type="button" id="addToCartBtn"><i class="fa fa-shopping-cart"></i>Adicionar Carrinho</button>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <h3 class="my-3">Detalhes</h3>
            <!-- Detail -->
            <table class="table table-bordered">
                <tr>
                    <th>Marca</th>
                    <td><a href="">{{data.marca.title}}</a></td>
                </tr>
                <tr>
                    <th>Categorias</th>
                    <td><a href="">{{data.category.title}}</a></td>
                </tr>
                <tr>
                    <th>Especificações</th>
                    <td><a href="">{{data.specs}}</a></td>
                </tr>
            </table>
        </div>
        <!-- Reviews -->
        <div class="col-md-6">
            <h3 class="my-3">Avaliações - <span class="avg-rating"></span>/5 <i class="fa fa-star text-warning"></i>
            
            
                <button data-toggle="modal" data-target="#productReview" type="button" class="btn btn-info btf-sm float-right reviewBtn">Adicionar Avaliação</button>

            </h3>

    <div class="modal fade" id="productReview" tabindex="-1" aria-labellebdy="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Adicionar Produto Avaliações</h5>
                    <button type="button" class="close" data-dismiss="model" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" id="addForm" action="">

                        <table class="table table-bordered">

                            <tr>
                                <td colspan="2">
                                    <button type="submit" class="btn btn-primary">Enviar</button>
                                    <input type="reset" class="btn btn-dark" value="Reset" id="Reset"/>
                                </td>
                            </tr>
                        </table>
                        <p class="ajaxRes"></p>
                    </form>
                </div>
            </div>
        </div>
    </div>

            </h3>
            <div class="card">
                <div class="card-body review-list" style="max-height: 400px; overflow: auto;">

                        <blockquote class="blockquote text-right">
                            <small></small>
                            <footer class="blockquote-footer">
                                <cite tilte="Source Title">

                                    <i class="fa fa-star text-warning"></i>
                                
                                </cite>
                            </footer>
                        </blockquote>
                        <hr />

                        <p class="no data">Adicionar Primeira Avaliação</p>

                </div>
            </div>
        </div>
    </div>

    <h3 class="mt-4 mb-3 border-bottom pb-1">Produtos Relacionados</h3>
    <div class="row">

        <div class="col-lg-3 col-sm-4 mb-4">
            <div class="card shadow">
                <a href=""><img src="" class="card-img-top" alt=""></a>
                <div class="card-body">
                    <h6 class="card-text"><a href="">{{product.title}}</a></h6>
                </div>
                <div class="card-footer">
                    <button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
                    <button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
                    <span class="float-right">
                        4.5/5
                        <i class="fa fa-star text-warning"></i>
                    </span>
                </div>
            </div>
        </div>
    
    </div>
</main>

<script src="{% static 'jquery.ex-plus.js' %}"></script>
<script type="text/javascript">
    $('#zoom_01').ezPlus();
</script>

<script src="{% static 'custom.js' %}"></script>

{% endblock %}

loja/main/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			
			<h3 class="mb-4 border-bottom pb-1">
				Produtos
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader"></p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
                            <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
                            <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.price}}" />
                            <input type="hidden" class="form-control product-qty-{{product.id}}" value="{{product.id}}" />
                            <input type="hidden" class="form-control product-qty-{{product.id}}" value="{{product.title}}" />
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index=""><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="" data-limit="3" class="btn btn-dark btn-sm">Carregar mais  <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}